extract_noun <- function(integrate_list)
{
  word_list <- sapply(integrate_list, extractNoun, USE.NAMES = F)
  word_list <- Filter(function(x){nchar(x)>=2}, unlist(word_list))
  word_list <- gsub("[A-z]","",word_list)
  word_list <- gsub("#*","",word_list)
  word_list <- gsub("/*","",word_list)
  word_list <- gsub("@*","",word_list)
  word_list <- gsub(",*","",word_list)
  word_list <- gsub("\"*","",word_list)
  word_list <- gsub("[0-9]","",word_list)
  word_list <- gsub("°*","",word_list)
  word_list <- gsub("…*","",word_list)
  word_list <- gsub("-*","",word_list)
  word_list <- gsub(":*","",word_list)
  word_list <- gsub("\\$*","",word_list)
  word_list <- gsub("&*","",word_list)
  word_list <- gsub("\\.*","",word_list)
  word_list <- gsub("서울*","",word_list)
  word_list <- gsub("\\(*","",word_list)
  word_list <- gsub("*그램","",word_list)
  word_list <- gsub("*)","",word_list)
  word_list <- gsub("*특별시","",word_list)
  word_list <- gsub("부산*","",word_list)
  word_list <- gsub("광역시*","",word_list)
  
  return (word_list)
}